DECLARE @TBTHONGKE TABLE(MaPB INT,LuongTB FLOAT)

INSERT INTO @TBTHONGKE
	SELECT PHG, AVG(LUONG) FROM NHANVIEN 
	GROUP BY PHG
SELECT * FROM @TBTHONGKE

SELECT TENNV, LUONG,
IIF(LUONG>LuongTB,'TRUONG PHONG','NHAN VIEN') AS 'CHUCVU'
FROM NHANVIEN
INNER JOIN @TBTHONGKE a
ON NHANVIEN.PHG = a.MaPB