DECLARE @B4 TABLE(TenPB NVARCHAR(20), SoLuong INT)
INSERT INTO @B4

SELECT TENPHG, COUNT (MaDA) FROM DEAN

INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = DEAN.PHONG
GROUP BY PHONG, TENPHG

SELECT * FROM @B4
