SELECT CONCAT(HONV, ' ', TENLOT, ' ', TENNV) as 'TenNV', LUONG from NHANVIEN
WHERE (
LUONG > (SELECT AVG(LUONG) FROM NHANVIEN
INNER JOIN PHONGBAN
ON NHANVIEN.PHG = PHONGBAN.MAPHG
WHERE PHONGBAN.TENPHG = N'Nghiên cứu')
)